"""Documents as knowledge (WORKFLOW.md B2.2, TASKS.md Phase 2b).

Box 1 of E1: answers that are paragraphs. FAQ pairs and uploaded documents land
in the same `knowledge_chunks` table under two population rules:

- FAQ: `embed_text` = the question, `content` = the answer (A4 symmetry);
- document: `embed_text` = `content` = the chunk's prose.

`questions` stays the FAQ authoring surface (Part D rule 6); `faq.py` mirrors
it here.
"""

from django.contrib.postgres.indexes import GinIndex
from django.contrib.postgres.search import SearchVector, SearchVectorField
from django.db import models
from pgvector.django import HnswIndex, VectorField

from company.models import Company
from questions.models import EMBEDDING_DIMENSIONS


class KnowledgeSource(models.Model):
    class Kind(models.TextChoices):
        FAQ = "faq", "FAQ pairs"
        DOCUMENT = "document", "Uploaded documents"
        URL = "url", "Web page"
        TEXT = "text", "Pasted text"

    class Status(models.TextChoices):
        EMPTY = "empty", "Empty"
        INDEXING = "indexing", "Indexing"
        READY = "ready", "Ready"
        FAILED = "failed", "Last ingestion failed"

    company = models.ForeignKey(Company, on_delete=models.CASCADE, related_name="knowledge_sources")
    chatbot = models.ForeignKey(
        "registry.Chatbot", on_delete=models.CASCADE, related_name="knowledge_sources"
    )
    name = models.CharField(max_length=255)
    kind = models.CharField(max_length=16, choices=Kind.choices)
    config = models.JSONField(default=dict, blank=True)
    status = models.CharField(max_length=16, choices=Status.choices, default=Status.EMPTY)
    last_indexed_at = models.DateTimeField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = "knowledge_sources"
        ordering = ("id",)
        constraints = [
            models.UniqueConstraint(
                fields=["chatbot"],
                condition=models.Q(kind="faq"),
                name="knowledge_sources_one_faq_per_chatbot",
            ),
        ]

    def __str__(self):
        return f"{self.name} ({self.kind})"


class KnowledgeDocument(models.Model):
    class Status(models.TextChoices):
        PENDING = "pending", "Waiting to be indexed"
        READY = "ready", "Indexed"
        FAILED = "failed", "Failed"

    source = models.ForeignKey(KnowledgeSource, on_delete=models.CASCADE, related_name="documents")
    # Filename for uploads, `question:<id>` for FAQ rows. Re-uploading the same
    # name replaces the document's chunks.
    external_ref = models.CharField(max_length=255)
    title = models.CharField(max_length=500, blank=True)
    raw_text = models.TextField(blank=True)
    # SHA-256 of the uploaded bytes: an unchanged re-upload is a no-op.
    checksum = models.CharField(max_length=64, blank=True)
    file_type = models.CharField(max_length=16, blank=True)
    status = models.CharField(max_length=16, choices=Status.choices, default=Status.PENDING)
    error = models.TextField(blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = "knowledge_documents"
        ordering = ("id",)
        constraints = [
            models.UniqueConstraint(
                fields=["source", "external_ref"], name="knowledge_documents_unique_ref"
            ),
        ]

    def __str__(self):
        return self.title or self.external_ref


class KnowledgeChunk(models.Model):
    chatbot = models.ForeignKey(
        "registry.Chatbot", on_delete=models.CASCADE, related_name="knowledge_chunks"
    )
    source = models.ForeignKey(KnowledgeSource, on_delete=models.CASCADE, related_name="chunks")
    document = models.ForeignKey(KnowledgeDocument, on_delete=models.CASCADE, related_name="chunks")
    ordinal = models.PositiveIntegerField(default=0)

    # What the model reads.
    content = models.TextField()
    # What the query is compared against.
    embed_text = models.TextField()
    embedding = VectorField(dimensions=EMBEDDING_DIMENSIONS, null=True, blank=True)
    # Per chunk, so a model upgrade can be indexed alongside the old one (B2.2).
    embedding_model = models.CharField(max_length=100, blank=True)

    # Full-text recall (B4). Generated by Postgres, so it can never drift from
    # the text it indexes. Covers the question too for FAQ rows.
    content_tsv = models.GeneratedField(
        expression=SearchVector("embed_text", "content", config="english"),
        output_field=SearchVectorField(),
        db_persist=True,
    )

    token_count = models.PositiveIntegerField(null=True, blank=True)
    # {document_title, section_heading, page} for documents; {kind, question_id} for FAQs.
    metadata = models.JSONField(default=dict, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table = "knowledge_chunks"
        ordering = ("document_id", "ordinal")
        indexes = [
            HnswIndex(
                name="kc_embedding_hnsw",
                fields=["embedding"],
                m=16,
                ef_construction=64,
                opclasses=["vector_cosine_ops"],
            ),
            GinIndex(fields=["content_tsv"], name="kc_tsv"),
            models.Index(fields=["chatbot", "source"], name="kc_tenant"),
        ]

    def __str__(self):
        return f"chunk {self.ordinal} of document {self.document_id}"


class IngestionJob(models.Model):
    """A background job with visible progress (TASKS.md 2b), not a request."""

    class Kind(models.TextChoices):
        DOCUMENT = "document", "Index a document"

    class Status(models.TextChoices):
        QUEUED = "queued", "Queued"
        RUNNING = "running", "Running"
        DONE = "done", "Done"
        FAILED = "failed", "Failed"

    company = models.ForeignKey(Company, on_delete=models.CASCADE, related_name="ingestion_jobs")
    source = models.ForeignKey(KnowledgeSource, on_delete=models.CASCADE, related_name="jobs")
    document = models.ForeignKey(
        KnowledgeDocument, on_delete=models.CASCADE, related_name="jobs", null=True, blank=True
    )
    kind = models.CharField(max_length=16, choices=Kind.choices, default=Kind.DOCUMENT)
    status = models.CharField(max_length=16, choices=Status.choices, default=Status.QUEUED)

    # The uploaded bytes, held only until the job has run.
    payload = models.BinaryField(blank=True, default=b"")
    filename = models.CharField(max_length=255, blank=True)

    total_steps = models.PositiveIntegerField(default=0)
    done_steps = models.PositiveIntegerField(default=0)
    message = models.CharField(max_length=255, blank=True)
    error = models.TextField(blank=True)

    created_at = models.DateTimeField(auto_now_add=True)
    started_at = models.DateTimeField(null=True, blank=True)
    finished_at = models.DateTimeField(null=True, blank=True)

    class Meta:
        db_table = "ingestion_jobs"
        ordering = ("-created_at", "-id")
        indexes = [models.Index(fields=["status", "created_at"], name="ingestion_jobs_queue_idx")]

    @property
    def progress(self) -> int:
        if self.status == self.Status.DONE:
            return 100
        if not self.total_steps:
            return 0
        return min(99, int(100 * self.done_steps / self.total_steps))
