# Generated by Django 5.2.15 on 2026-06-22 19:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('knowledge_base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('date', models.DateField(db_index=True)),
                ('total_conversations', models.PositiveIntegerField(default=0)),
                ('resolved_by_ai', models.PositiveIntegerField(default=0)),
                ('resolved_by_agent', models.PositiveIntegerField(default=0)),
                ('escalated_chats', models.PositiveIntegerField(default=0)),
                ('avg_response_time', models.FloatField(default=0.0)),
                ('avg_resolution_time', models.FloatField(default=0.0)),
                ('top_questions', models.JSONField(blank=True, default=list)),
                ('unanswered_questions', models.PositiveIntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='companies.company')),
            ],
            options={
                'db_table': 'analytics_conversation_metrics',
                'ordering': ['-date'],
                'constraints': [models.UniqueConstraint(fields=('company', 'date'), name='uniq_company_date_metrics')],
            },
        ),
        migrations.CreateModel(
            name='UnansweredQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('question', models.TextField()),
                ('normalized', models.CharField(db_index=True, max_length=512)),
                ('occurrence_count', models.PositiveIntegerField(default=1)),
                ('is_resolved', models.BooleanField(db_index=True, default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unanswered_questions', to='companies.company')),
                ('converted_qa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='knowledge_base.questionanswer')),
            ],
            options={
                'db_table': 'analytics_unanswered_question',
                'ordering': ['-occurrence_count', '-updated_at'],
                'constraints': [models.UniqueConstraint(fields=('company', 'normalized'), name='uniq_company_unanswered')],
            },
        ),
    ]
