# Generated by Django 5.2.17 on 2026-09-14 12:38

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
import pgvector.django.indexes
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0002_alter_company_options'),
        ('registry', '0002_backfill_chatbots'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('kind', models.CharField(choices=[('faq', 'FAQ pairs'), ('document', 'Uploaded documents'), ('url', 'Web page'), ('text', 'Pasted text')], max_length=16)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('empty', 'Empty'), ('indexing', 'Indexing'), ('ready', 'Ready'), ('failed', 'Last ingestion failed')], default='empty', max_length=16)),
                ('last_indexed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chatbot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_sources', to='registry.chatbot')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_sources', to='company.company')),
            ],
            options={
                'db_table': 'knowledge_sources',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='KnowledgeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_ref', models.CharField(max_length=255)),
                ('title', models.CharField(blank=True, max_length=500)),
                ('raw_text', models.TextField(blank=True)),
                ('checksum', models.CharField(blank=True, max_length=64)),
                ('file_type', models.CharField(blank=True, max_length=16)),
                ('status', models.CharField(choices=[('pending', 'Waiting to be indexed'), ('ready', 'Indexed'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='knowledge.knowledgesource')),
            ],
            options={
                'db_table': 'knowledge_documents',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='KnowledgeChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordinal', models.PositiveIntegerField(default=0)),
                ('content', models.TextField()),
                ('embed_text', models.TextField()),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=384, null=True)),
                ('embedding_model', models.CharField(blank=True, max_length=100)),
                ('content_tsv', models.GeneratedField(db_persist=True, expression=django.contrib.postgres.search.SearchVector('embed_text', 'content', config='english'), output_field=django.contrib.postgres.search.SearchVectorField())),
                ('token_count', models.PositiveIntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chatbot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_chunks', to='registry.chatbot')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='knowledge.knowledgedocument')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='knowledge.knowledgesource')),
            ],
            options={
                'db_table': 'knowledge_chunks',
                'ordering': ('document_id', 'ordinal'),
            },
        ),
        migrations.CreateModel(
            name='IngestionJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('document', 'Index a document')], default='document', max_length=16)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('done', 'Done'), ('failed', 'Failed')], default='queued', max_length=16)),
                ('payload', models.BinaryField(blank=True, default=b'')),
                ('filename', models.CharField(blank=True, max_length=255)),
                ('total_steps', models.PositiveIntegerField(default=0)),
                ('done_steps', models.PositiveIntegerField(default=0)),
                ('message', models.CharField(blank=True, max_length=255)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingestion_jobs', to='company.company')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='knowledge.knowledgedocument')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='knowledge.knowledgesource')),
            ],
            options={
                'db_table': 'ingestion_jobs',
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.AddConstraint(
            model_name='knowledgesource',
            constraint=models.UniqueConstraint(condition=models.Q(('kind', 'faq')), fields=('chatbot',), name='knowledge_sources_one_faq_per_chatbot'),
        ),
        migrations.AddConstraint(
            model_name='knowledgedocument',
            constraint=models.UniqueConstraint(fields=('source', 'external_ref'), name='knowledge_documents_unique_ref'),
        ),
        migrations.AddIndex(
            model_name='knowledgechunk',
            index=pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='kc_embedding_hnsw', opclasses=['vector_cosine_ops']),
        ),
        migrations.AddIndex(
            model_name='knowledgechunk',
            index=django.contrib.postgres.indexes.GinIndex(fields=['content_tsv'], name='kc_tsv'),
        ),
        migrations.AddIndex(
            model_name='knowledgechunk',
            index=models.Index(fields=['chatbot', 'source'], name='kc_tenant'),
        ),
        migrations.AddIndex(
            model_name='ingestionjob',
            index=models.Index(fields=['status', 'created_at'], name='ingestion_jobs_queue_idx'),
        ),
    ]
