"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.15.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from datetime import timedelta
from pathlib import Path
import os
import warnings

from dotenv import load_dotenv


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from the .env file at the project root.
load_dotenv(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-+1%9h!#m$9az1+i-7$c(z67$zikkfcny8qiotsxjm%lg&i-jne'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    # `daphne` must come first: it swaps in the ASGI-aware runserver so the
    # WebSocket routing below is served in development.
    'daphne',
    'channels',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'company',
    'users',
    'questions',
    'vector_question',
    'rest_framework',
    'corsheaders',
    'chat',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # CORS must come before CommonMiddleware so it can add headers to responses.
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'

# Channels drives the WebSocket side of the app (the chatbot socket).
ASGI_APPLICATION = 'config.asgi.application'

# Channel layer. The in-memory backend keeps groups inside a single process,
# so agent handoff silently stops working the moment a second worker exists —
# set REDIS_URL for anything beyond a single-process dev server.
REDIS_URL = os.getenv("REDIS_URL", "")

if REDIS_URL:
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels_redis.core.RedisChannelLayer",
            "CONFIG": {"hosts": [REDIS_URL]},
        },
    }
else:
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels.layers.InMemoryChannelLayer",
        },
    }
    warnings.warn(
        "REDIS_URL is not set - using the in-memory channel layer. Chat "
        "handoff between the customer widget and the agent console only works "
        "within one process. Do not deploy this way.",
        RuntimeWarning,
        stacklevel=1,
    )


# --- DRF --------------------------------------------------------------------
# Closed by default: every endpoint requires a bearer token unless it opts out
# with `permission_classes = [AllowAny]`. The alternative (open by default,
# lock down individually) is how the previous `?user_type=Admin` check ended up
# being the only thing standing between the internet and every tenant's data.
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "users.authentication.BearerTokenAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "users.permissions.IsAuthenticatedUser",
    ],
    # We do not use django.contrib.auth, so there is no AnonymousUser to fall
    # back to; permission classes treat None as "not signed in".
    "UNAUTHENTICATED_USER": None,
}

# CORS — allow the Vite dev server (frontend) to call this API.
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "http://127.0.0.1:5173",
]


# Logging — without this, app loggers fall through to the root logger (level
# WARNING), so logger.info(...) calls are silently dropped. Route everything
# to the console at INFO in development.
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "simple": {
            "format": "{levelname} {name} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "simple",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "INFO",
    },
}


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.getenv("DB_NAME", "temp_chatbot"),
        "USER": os.getenv("DB_USER", "postgres"),
        "PASSWORD": os.getenv("DB_PASSWORD", "postgres"),
        "HOST": os.getenv("DB_HOST", "localhost"),
        "PORT": os.getenv("DB_PORT", "5432"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# --- Chatbot / LLM ----------------------------------------------------------
# The chatbot retrieves the top matching FAQ questions, then asks Gemini to
# answer using only those as context.
GEMINI_API_KEY = os.getenv("GEMINI_API_KEY", "")
GEMINI_MODEL = os.getenv("GEMINI_MODEL", "gemini-2.5-flash")
# Retrieval floor: below this cosine score the best FAQ match is not even shown
# to the LLM, and the chat is handed to a human agent.
#
# Measured on all-MiniLM-L6-v2 with bare-question index text (the bands are
# pinned by tests/test_retrieval.py):
#
#     exact restatement      1.00
#     true paraphrase        0.44 - 0.80
#     unrelated question     0.08 - 0.35
#
# The usable separation is a narrow 0.35-0.44 band, and 0.40 sits inside it.
# This was 0.90 - far above anything the model produces for a paraphrase - so
# essentially every rephrased question escalated to a human.
#
# Treat this as a cheap pre-filter, not the decision: `generate_answer` returns
# `is_answer_found`, and that second, LLM-side judgement is what decides whether
# the FAQ context actually answers the question. Erring low here is therefore
# the safe direction.
DEFAULT_CHAT_CONFIDENCE_THRESHOLD = 0.40
CHAT_CONFIDENCE_THRESHOLD = float(
    os.getenv("CHAT_CONFIDENCE_THRESHOLD", str(DEFAULT_CHAT_CONFIDENCE_THRESHOLD))
) 
