# Generated by Django 5.2.15 on 2026-07-01 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_vectorized',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='vector_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
