# Generated by Django 5.2.15 on 2026-07-25 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_alter_company_options'),
        ('questions', '0003_question_embedding'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnansweredMessage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unanswered_messages', to='company.company')),
            ],
            options={
                'db_table': 'unanswered_messages',
                'ordering': ('-timestamp',),
            },
        ),
    ]
