# Generated by Django 5.2.15 on 2026-06-22 19:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WidgetConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(default='Support', max_length=255)),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('position', models.CharField(choices=[('bottom-right', 'Bottom right'), ('bottom-left', 'Bottom left')], default='bottom-right', max_length=16)),
                ('primary_color', models.CharField(default='#4f46e5', max_length=9)),
                ('launcher_icon', models.URLField(blank=True)),
                ('allowed_origins', models.JSONField(blank=True, default=list)),
                ('collect_visitor_email', models.BooleanField(default=False)),
                ('enabled', models.BooleanField(default=True)),
                ('chatbot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='widget_config', to='chatbot.chatbot')),
            ],
            options={
                'db_table': 'integrations_widget_config',
            },
        ),
    ]
