# Generated by Django 5.2.17 on 2026-09-09 13:43

import django.core.validators
import django.db.models.deletion
import registry.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0002_alter_company_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chatbot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('persona_prompt', models.TextField(blank=True)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('temperature', models.FloatField(default=0.2, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(2.0)])),
                ('locale', models.CharField(default='en', max_length=16)),
                ('is_active', models.BooleanField(default=True)),
                ('policy', models.JSONField(blank=True, default=registry.models.default_policy)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chatbots', to='company.company')),
            ],
            options={
                'db_table': 'chatbots',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('tool_type', models.CharField(choices=[('KNOWLEDGE_SEARCH', 'Knowledge search'), ('STRUCTURED_SEARCH', 'Structured search'), ('API_ACTION', 'API action'), ('HANDOFF', 'Handoff')], max_length=32)),
                ('configuration', models.JSONField(blank=True, default=dict)),
                ('input_schema', models.JSONField(blank=True, default=dict)),
                ('schema_version', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('requires_confirmation', models.BooleanField(default=False)),
                ('rate_limit', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chatbot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tools', to='registry.chatbot')),
            ],
            options={
                'db_table': 'tools',
                'ordering': ('chatbot_id', 'id'),
            },
        ),
        migrations.AddIndex(
            model_name='chatbot',
            index=models.Index(fields=['company', 'is_active'], name='chatbots_company_idx'),
        ),
        migrations.AddIndex(
            model_name='tool',
            index=models.Index(fields=['chatbot', 'is_active'], name='tools_chatbot_idx'),
        ),
        migrations.AddConstraint(
            model_name='tool',
            constraint=models.UniqueConstraint(fields=('chatbot', 'name'), name='tools_unique_name_per_chatbot'),
        ),
    ]
