# Generated by Django 5.2.17 on 2026-09-14 12:17

import django.contrib.postgres.fields
import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0002_alter_company_options'),
        ('registry', '0002_backfill_chatbots'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=48, validators=[django.core.validators.RegexValidator('^[a-z][a-z0-9_]*$', 'Use lowercase letters, digits and underscores, starting with a letter.')])),
                ('display_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('adapter', models.CharField(choices=[('records', 'Records (uploaded rows)'), ('rest_api', 'REST API'), ('sql_readonly', 'Read-only SQL')], default='records', max_length=16)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('row_count', models.PositiveIntegerField(default=0)),
                ('sync_status', models.CharField(choices=[('empty', 'No data yet'), ('ready', 'Ready'), ('failed', 'Last import failed')], default='empty', max_length=16)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('schema_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chatbot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_sources', to='registry.chatbot')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_sources', to='company.company')),
            ],
            options={
                'db_table': 'data_sources',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='DataRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=255)),
                ('payload', models.JSONField(default=dict)),
                ('search_tsv', django.contrib.postgres.search.SearchVectorField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('data_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='datasources.datasource')),
            ],
            options={
                'db_table': 'data_records',
            },
        ),
        migrations.CreateModel(
            name='DataSourceField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator('^[a-z][a-z0-9_]*$', 'Use lowercase letters, digits and underscores, starting with a letter.')])),
                ('label', models.CharField(blank=True, max_length=255)),
                ('data_type', models.CharField(choices=[('string', 'Text'), ('integer', 'Whole number'), ('number', 'Number'), ('boolean', 'Yes / no'), ('date', 'Date'), ('datetime', 'Date and time'), ('string_array', 'List of values')], max_length=16)),
                ('path', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('unit', models.CharField(blank=True, max_length=32)),
                ('is_exposed', models.BooleanField(default=True)),
                ('is_filterable', models.BooleanField(default=True)),
                ('is_sortable', models.BooleanField(default=False)),
                ('is_searchable', models.BooleanField(default=False)),
                ('is_returned', models.BooleanField(default=True)),
                ('allowed_operators', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=16), blank=True, default=list, size=None)),
                ('enum_values', models.JSONField(blank=True, null=True)),
                ('cardinality', models.PositiveIntegerField(blank=True, null=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('data_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='datasources.datasource')),
            ],
            options={
                'db_table': 'data_source_fields',
                'ordering': ('display_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='DataSourceSync',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('upsert', 'Upsert (keep rows not in the file)'), ('replace', 'Replace (remove rows not in the file)')], default='upsert', max_length=16)),
                ('filename', models.CharField(blank=True, max_length=255)),
                ('rows_in', models.PositiveIntegerField(default=0)),
                ('rows_upserted', models.PositiveIntegerField(default=0)),
                ('rows_rejected', models.PositiveIntegerField(default=0)),
                ('errors', models.JSONField(blank=True, default=list)),
                ('warnings', models.JSONField(blank=True, default=list)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('data_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='syncs', to='datasources.datasource')),
            ],
            options={
                'db_table': 'data_source_syncs',
                'ordering': ('-started_at', '-id'),
            },
        ),
        migrations.AddConstraint(
            model_name='datasource',
            constraint=models.UniqueConstraint(fields=('chatbot', 'name'), name='data_sources_unique_name_per_chatbot'),
        ),
        migrations.AddIndex(
            model_name='datarecord',
            index=django.contrib.postgres.indexes.GinIndex(fields=['payload'], name='data_records_payload_gin', opclasses=['jsonb_path_ops']),
        ),
        migrations.AddIndex(
            model_name='datarecord',
            index=models.Index(fields=['data_source', 'deleted_at'], name='data_records_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='datarecord',
            constraint=models.UniqueConstraint(fields=('data_source', 'external_id'), name='data_records_unique_external_id'),
        ),
        migrations.AddConstraint(
            model_name='datasourcefield',
            constraint=models.UniqueConstraint(fields=('data_source', 'name'), name='data_source_fields_unique_name'),
        ),
    ]
