# Generated by Django 5.2.15 on 2026-06-22 19:08

import django.db.models.deletion
import pgvector.django.indexes
import pgvector.django.vector
import uuid
from django.db import migrations, models
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        # Enable the pgvector PostgreSQL extension before any vector column /
        # index is created. Requires the DB role to have CREATE privilege; on
        # managed Postgres run `CREATE EXTENSION vector;` once as superuser.
        VectorExtension(),
        migrations.CreateModel(
            name='KnowledgeBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_bases', to='companies.company')),
            ],
            options={
                'db_table': 'kb_knowledge_base',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuestionAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('embedding_status', models.CharField(choices=[('PENDING', 'Pending'), ('READY', 'Ready'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=16)),
                ('knowledge_base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qa_pairs', to='knowledge_base.knowledgebase')),
            ],
            options={
                'db_table': 'kb_question_answer',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuestionEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('embedding', pgvector.django.vector.VectorField(dimensions=1536)),
                ('model_name', models.CharField(blank=True, max_length=128)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_embeddings', to='companies.company')),
                ('qa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='embedding', to='knowledge_base.questionanswer')),
            ],
            options={
                'db_table': 'kb_question_embedding',
            },
        ),
        migrations.AddIndex(
            model_name='knowledgebase',
            index=models.Index(fields=['company', 'is_active'], name='kb_knowledg_company_3c4dde_idx'),
        ),
        migrations.AddIndex(
            model_name='questionanswer',
            index=models.Index(fields=['knowledge_base', 'embedding_status'], name='kb_question_knowled_299d19_idx'),
        ),
        migrations.AddIndex(
            model_name='questionembedding',
            index=pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='qa_embedding_hnsw', opclasses=['vector_cosine_ops']),
        ),
        migrations.AddIndex(
            model_name='questionembedding',
            index=models.Index(fields=['company'], name='kb_question_company_bfeab0_idx'),
        ),
    ]
