# Generated by Codex on 2026-07-23

from django.db import migrations, models


def forwards(apps, schema_editor):
    User = apps.get_model("users", "User")
    User.objects.filter(type="Employee").update(type="Agent")


def backwards(apps, schema_editor):
    User = apps.get_model("users", "User")
    User.objects.filter(type="Agent").update(type="Employee")


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_password"),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
        migrations.AlterField(
            model_name="user",
            name="type",
            field=models.CharField(
                choices=[("Admin", "Admin"), ("Agent", "Agent"), ("Manager", "Manager")],
                max_length=10,
            ),
        ),
    ]
