# Generated by Django 5.2.15 on 2026-07-01 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={},
        ),
    ]
