# Generated by Django 5.2.17 on 2026-09-14 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chatsession_public_token'),
        ('company', '0002_alter_company_options'),
        ('registry', '0002_backfill_chatbots'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'ordering': ['created_at', 'id']},
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='latency_ms',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('tool', 'Tool'), ('system', 'System')], default='user', max_length=16),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='tokens',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='tool_args',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='tool_call_id',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='tool_name',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='tool_result',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='tool_result_summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='channel',
            field=models.CharField(default='web', max_length=32),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='chatbot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_sessions', to='registry.chatbot'),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='summary_upto_message_id',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='visitor_id',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='working_set',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='ToolExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_name', models.CharField(max_length=64)),
                ('raw_arguments', models.JSONField(blank=True, default=dict)),
                ('validated_arguments', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ok', 'OK'), ('rejected', 'Rejected by a gate'), ('error', 'Executor error'), ('timeout', 'Timed out'), ('cached', 'Repeat call served from cache'), ('rate_limited', 'Rate limited')], max_length=16)),
                ('error_code', models.CharField(blank=True, max_length=64)),
                ('rows_returned', models.PositiveIntegerField(blank=True, null=True)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool_executions', to='company.company')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool_executions', to='chat.chatsession')),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tool_executions', to='chat.chatmessage')),
                ('tool', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executions', to='registry.tool')),
            ],
            options={
                'db_table': 'tool_executions',
                'ordering': ['created_at', 'id'],
                'indexes': [models.Index(fields=['conversation', 'tool_name'], name='tool_exec_conversation_idx')],
            },
        ),
    ]
