# Generated by Django 5.2.17 on 2026-09-14 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_backfill_roles_and_chatbots'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolexecution',
            name='compiled_query',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
