# Generated by Django 5.2.15 on 2026-07-01 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0002_alter_company_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='VectorJob',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('total_questions', models.PositiveIntegerField(default=0)),
                ('processed_questions', models.PositiveIntegerField(default=0)),
                ('failed_questions', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vector_jobs', to='company.company')),
            ],
            options={
                'db_table': 'vector_jobs',
                'ordering': ['-created_at'],
            },
        ),
    ]
