# Generated by Django 5.2.15 on 2026-06-22 19:08

import chatbot.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chatbot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('welcome_message', models.TextField(default='Hi! How can I help you today?')),
                ('theme_color', models.CharField(default='#4f46e5', max_length=9)),
                ('widget_token', models.CharField(db_index=True, default=chatbot.models.generate_widget_token, max_length=64, unique=True)),
                ('system_prompt', models.TextField(blank=True)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chatbots', to='companies.company')),
            ],
            options={
                'db_table': 'chatbot_chatbot',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('session_id', models.CharField(db_index=True, max_length=128)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('chatbot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitors', to='chatbot.chatbot')),
            ],
            options={
                'db_table': 'chatbot_visitor',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('chatbot', 'session_id'), name='uniq_visitor_session')],
            },
        ),
    ]
